"""initial operational schema

Revision ID: 534503dc59e6
Revises: 
Create Date: 2026-08-03 22:30:40.324994
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '534503dc59e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('legal_entity', sa.String(length=160), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('manager_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=True)
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('client_id_reference', sa.String(length=160), nullable=True),
    sa.Column('encrypted_secret_placeholder', sa.Text(), nullable=True),
    sa.Column('key_identifier', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'provider', name='uq_credential_shop_provider')
    )
    op.create_index(op.f('ix_api_credentials_shop_id'), 'api_credentials', ['shop_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_shop_id'), 'audit_events', ['shop_id'], unique=False)
    op.create_table('listing_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.String(length=64), nullable=True),
    sa.Column('primary_image_url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'offer_id', name='uq_listing_draft_shop_offer')
    )
    op.create_index(op.f('ix_listing_drafts_shop_id'), 'listing_drafts', ['shop_id'], unique=False)
    op.create_index(op.f('ix_listing_drafts_status'), 'listing_drafts', ['status'], unique=False)
    op.create_table('ozon_category_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'category_id', 'type_id', name='uq_category_cache')
    )
    op.create_index(op.f('ix_ozon_category_cache_shop_id'), 'ozon_category_cache', ['shop_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('ozon_product_id', sa.String(length=64), nullable=False),
    sa.Column('offer_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'ozon_product_id', name='uq_product_shop_ozon_id')
    )
    op.create_index(op.f('ix_products_shop_id'), 'products', ['shop_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_run_shop_resource_started', 'sync_runs', ['shop_id', 'resource', 'started_at'], unique=False)
    op.create_index(op.f('ix_sync_runs_shop_id'), 'sync_runs', ['shop_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_table('sync_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=40), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('window_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'resource', name='uq_sync_state_shop_resource')
    )
    op.create_index('ix_sync_state_freshness', 'sync_states', ['shop_id', 'resource', 'last_success_at'], unique=False)
    op.create_index('ix_sync_state_lease', 'sync_states', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_sync_states_shop_id'), 'sync_states', ['shop_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pickup_point', sa.String(length=160), nullable=True),
    sa.Column('cutoff_time', sa.String(length=5), nullable=True),
    sa.Column('workdays', sa.String(length=64), nullable=True),
    sa.Column('carrier', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_warehouse_shop_name')
    )
    op.create_index(op.f('ix_warehouses_shop_id'), 'warehouses', ['shop_id'], unique=False)
    op.create_table('fbs_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('posting_number', sa.String(length=128), nullable=False),
    sa.Column('normalized_status', sa.String(length=40), nullable=False),
    sa.Column('raw_ozon_status', sa.String(length=128), nullable=True),
    sa.Column('pack_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'posting_number', name='uq_posting_shop_number')
    )
    op.create_index(op.f('ix_fbs_postings_normalized_status'), 'fbs_postings', ['normalized_status'], unique=False)
    op.create_index(op.f('ix_fbs_postings_pack_by'), 'fbs_postings', ['pack_by'], unique=False)
    op.create_index(op.f('ix_fbs_postings_shop_id'), 'fbs_postings', ['shop_id'], unique=False)
    op.create_table('listing_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('seller_sku', sa.String(length=128), nullable=False),
    sa.Column('purchase_cost_cny', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('weight_g', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('width_mm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('height_mm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('calculated_price_cny', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_price_cny', sa.String(length=32), nullable=True),
    sa.Column('old_price_cny', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['listing_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'seller_sku', name='uq_listing_variant_draft_sku')
    )
    op.create_index(op.f('ix_listing_variants_draft_id'), 'listing_variants', ['draft_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_sku', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('min_price_cny', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'seller_sku', name='uq_sku_shop_seller_sku')
    )
    op.create_index(op.f('ix_skus_product_id'), 'skus', ['product_id'], unique=False)
    op.create_index(op.f('ix_skus_shop_id'), 'skus', ['shop_id'], unique=False)
    op.create_table('fbs_posting_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(length=128), nullable=False),
    sa.Column('ozon_product_id', sa.String(length=64), nullable=True),
    sa.Column('ozon_sku', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('image_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['fbs_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posting_id', 'offer_id', name='uq_posting_line_offer')
    )
    op.create_index(op.f('ix_fbs_posting_lines_posting_id'), 'fbs_posting_lines', ['posting_id'], unique=False)
    op.create_table('inventory_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'sku_id', name='uq_inventory_warehouse_sku')
    )
    op.create_index(op.f('ix_inventory_balances_shop_id'), 'inventory_balances', ['shop_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_sku_id'), 'inventory_balances', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_warehouse_id'), 'inventory_balances', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_balances_warehouse_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_sku_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_inventory_balances_shop_id'), table_name='inventory_balances')
    op.drop_table('inventory_balances')
    op.drop_index(op.f('ix_fbs_posting_lines_posting_id'), table_name='fbs_posting_lines')
    op.drop_table('fbs_posting_lines')
    op.drop_index(op.f('ix_skus_shop_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_product_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_listing_variants_draft_id'), table_name='listing_variants')
    op.drop_table('listing_variants')
    op.drop_index(op.f('ix_fbs_postings_shop_id'), table_name='fbs_postings')
    op.drop_index(op.f('ix_fbs_postings_pack_by'), table_name='fbs_postings')
    op.drop_index(op.f('ix_fbs_postings_normalized_status'), table_name='fbs_postings')
    op.drop_table('fbs_postings')
    op.drop_index(op.f('ix_warehouses_shop_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_sync_states_shop_id'), table_name='sync_states')
    op.drop_index('ix_sync_state_lease', table_name='sync_states')
    op.drop_index('ix_sync_state_freshness', table_name='sync_states')
    op.drop_table('sync_states')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_shop_id'), table_name='sync_runs')
    op.drop_index('ix_sync_run_shop_resource_started', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_products_shop_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ozon_category_cache_shop_id'), table_name='ozon_category_cache')
    op.drop_table('ozon_category_cache')
    op.drop_index(op.f('ix_listing_drafts_status'), table_name='listing_drafts')
    op.drop_index(op.f('ix_listing_drafts_shop_id'), table_name='listing_drafts')
    op.drop_table('listing_drafts')
    op.drop_index(op.f('ix_audit_events_shop_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_api_credentials_shop_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
