"""add listing attribute cache

Revision ID: 6e31c4c72bd0
Revises: 534503dc59e6
Create Date: 2026-08-03 22:57:09.261532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e31c4c72bd0'
down_revision: Union[str, Sequence[str], None] = '534503dc59e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_attribute_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('attribute_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('dictionary_id', sa.String(length=64), nullable=False),
    sa.Column('value_type', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'category_id', 'type_id', 'attribute_id', name='uq_ozon_attribute_cache')
    )
    op.create_index(op.f('ix_ozon_attribute_cache_shop_id'), 'ozon_attribute_cache', ['shop_id'], unique=False)
    op.create_table('ozon_attribute_dictionary_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('attribute_id', sa.String(length=64), nullable=False),
    sa.Column('value_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'category_id', 'type_id', 'attribute_id', 'value_id', name='uq_ozon_attribute_dictionary_value')
    )
    op.create_index(op.f('ix_ozon_attribute_dictionary_values_shop_id'), 'ozon_attribute_dictionary_values', ['shop_id'], unique=False)
    op.create_table('ozon_attribute_dictionary_query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('attribute_id', sa.String(length=64), nullable=False),
    sa.Column('query_key', sa.String(length=100), nullable=False),
    sa.Column('result_limit', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'category_id', 'type_id', 'attribute_id', 'query_key', 'result_limit', name='uq_ozon_attribute_dictionary_query_cache')
    )
    op.create_index(op.f('ix_ozon_attribute_dictionary_query_cache_shop_id'), 'ozon_attribute_dictionary_query_cache', ['shop_id'], unique=False)
    op.create_table('listing_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('value_id', sa.String(length=64), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['listing_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'attribute_id', name='uq_listing_attribute_draft_attribute')
    )
    op.create_index(op.f('ix_listing_attribute_values_draft_id'), 'listing_attribute_values', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_attribute_values_draft_id'), table_name='listing_attribute_values')
    op.drop_table('listing_attribute_values')
    op.drop_index(op.f('ix_ozon_attribute_dictionary_query_cache_shop_id'), table_name='ozon_attribute_dictionary_query_cache')
    op.drop_table('ozon_attribute_dictionary_query_cache')
    op.drop_index(op.f('ix_ozon_attribute_dictionary_values_shop_id'), table_name='ozon_attribute_dictionary_values')
    op.drop_table('ozon_attribute_dictionary_values')
    op.drop_index(op.f('ix_ozon_attribute_cache_shop_id'), table_name='ozon_attribute_cache')
    op.drop_table('ozon_attribute_cache')
    # ### end Alembic commands ###
